### ISSUE TITLE
What this library is for?

### ISSUE THREAD

**Issue by Igorgro** [microsoft/dev-tunnels#235]
This library looks very interesting, but there is no any description about the prupose of it. Is it somehow connected with VSCode Remote extensions?

**Comment by derekbekoe** [comment]
This repository contains SDKs used to interact with the Dev Tunnels service.
Learn more at https://techcommunity.microsoft.com/t5/azure-developer-community-blog/announcing-the-public-preview-of-the-devtunnel-cli/ba-p/3823131

VS Code Remote Tunnels uses the Dev Tunnels sdk behind-the-scenes.
