### ISSUE TITLE
DevTunnel inspect is not working with browser set to italian language

### ISSUE THREAD

**Issue by AngeloDotNet** [microsoft/dev-tunnels#247]
This call (https://??????-4443-inspect.euw.devtunnels.ms/core/i18n/locales/it.json) with the browser in Italian returns a 404 error.
By setting the browser to English, however, this error is not encountered.

**Comment by jfullerton44** [comment]
> @AngeloDotNet thanks for trying out dev tunnels and reporting your issue. We'll take a look and follow-up if we have further questions.
> 
> Just to confirm usage of tunnel inspection, to inspect a tunnel `https://??????-4443-inspect.euw.devtunnels.ms` is sufficient. No path needs to be specified.

The (https://??????-4443-inspect.euw.devtunnels.ms/core/i18n/locales/it.json) url is just a file that is loaded based on the user's browser language. It is requested when the user first opens inspection. I can look into adding other language files.

**Comment by jfullerton44** [comment]
@AngeloDotNet We have merged a fix, can you verify that you can access the page in italian now?

**Comment by AngeloDotNet** [comment]
@jfullerton44 at the moment I don't have the possibility to try, I will do a test tomorrow June 21st and after that I will update this issue.

**Comment by AngeloDotNet** [comment]
Hello @jfullerton44, I confirm that now it works correctly also with the browser in Italian. Thank you

![image](https://github.com/microsoft/dev-tunnels/assets/49655304/8eec6b25-df82-4867-8165-110621d5f8e6)
