### ISSUE TITLE
devtunnel CLI: Add support for linux arm32

### ISSUE THREAD

**Issue by ali50m** [microsoft/dev-tunnels#250]
I would like to host/test a dotnet asp api on my raspberry Pi. But it seems `devtunnel cli` doesnot work on it.

### steps:
1. run the following command on Pi4 accoordind to the instructions on [link](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=linux#install)
```bash
curl -sL https://aka.ms/DevTunnelCliInstall | bash
```

2. Here is the output of installation command
```
Downloading the devtunnel CLI...
Selecting previously unselected package libsecret-common.
(Reading database ... 45756 files and directories currently installed.)
Preparing to unpack .../libsecret-common_0.20.4-2_all.deb ...
Unpacking libsecret-common (0.20.4-2) ...
Selecting previously unselected package libsecret-1-0:armhf.
Preparing to unpack .../libsecret-1-0_0.20.4-2_armhf.deb ...
Unpacking libsecret-1-0:armhf (0.20.4-2) ...
Setting up libsecret-common (0.20.4-2) ...
Setting up libsecret-1-0:armhf (0.20.4-2) ...
Processing triggers for libc-bin (2.31-13+rpt2+rpi1+deb11u5) ...
devtunnel CLI installed!

Version:
bash: line 71: /root/bin/devtunnel: No such file or directory
    

To get started, run:
    source ~/.bashrc
    devtunnel -h
```

3. after source import the bashrc and run devtunnel, even I reboot the device,  this devtunnel cli tool always report
```
-bash: /root/bin/devtunnel: No such file or directory
```

### environment
+ raspberry Pi 4B with 4G ram
+ 2023-05-03-raspios-bullseye-armhf-lite.img installed

**Comment by curib** [comment]
@ali50m, thank you for opening an issue! We're adding this ask to our backlog and we'll respond here once we have an update or any additional questions.

**Comment by setaskin** [comment]
Hi @ali50m , we just released linux arm 32 supported version. You can install the same link you posted above. Thank you for your patience.
