### ISSUE TITLE
How to set access to organization via CLI

### ISSUE THREAD

**Issue by theblindprophet** [microsoft/dev-tunnels#252]
I cannot seem to find how to set the access of the tunnel to organization. By default, it is private.

This documentation does not explain it: https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands

**Comment by curib** [comment]
@theblindprophet, thank you for opening an issue for this! To set the access of a dev tunnel to members of your organization only, you will have to use dev tunnels for Visual Studio. I have good news though; you'll soon be able to do that in the CLI too. We'll update this issue and the documentation once that's available.

**Comment by curib** [comment]
@theblindprophet, you can now set the access of the tunnel to your organization through the CLI. To do so, you'll just need to run `devtunnel access create TUNNELID --tenant ` after creating/hosting your tunnel.

Our doc updates will be live next week. Thank you again for opening this issue!
