### ISSUE TITLE
DevTunnel CLI open source?

### ISSUE THREAD

**Issue by DomenPigeon** [microsoft/dev-tunnels#258]
Will the cli project for devTunnel also be open source? I coudn't find it currenlty.

**Comment by curib** [comment]
@DomenPigeon, thank you for reaching out! We don't have plans to open source the devtunnel CLI at this time. If that ever changes though, we'll update this issue.

**Comment by Aungkhant884** [comment]
@

- [ ] @DomenPigeon

**Comment by derekbekoe** [comment]
We don't have plans to open-source the CLI.
I'll be closing this issue but if we do re-visit this, we'll re-open.
