### ISSUE TITLE
Support HTTP/2 on devtunnels.ms

### ISSUE THREAD

**Issue by mayuki** [microsoft/dev-tunnels#263]
I started a gRPC server on ASP.NET Core and then tried to access it from a client through Dev Tunnels.

The client throws the following exception:
>Grpc.Core.RpcException: 'Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.", DebugException="System.Net.Http.HttpRequestException: Requesting HTTP version 2.0 with version policy RequestVersionOrHigher while unable to establish HTTP/2 connection.")'

The tunnel appears to downgrade HTTP requests, is it not compatible with HTTP/2?

**Comment by derekbekoe** [comment]
We do not currently support HTTP/2 via `*devtunnels.ms`. However, this should be possible via the `devtunnel connect TUNNELID` command documented on this page - https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands. With this, the client can connect to your grpc server via `localhost:PORT`.

I've marked this as a feature request for support HTTP/2 on `*.devtunnels.ms` but let us know if the above works.

**Comment by mayuki** [comment]
Thanks. I confirmed the connection with the client using devtunnel-cli and gRPC (HTTP/2). 
I look forward to supporting HTTP/2 on `*.devtunnels.ms`.

**Comment by derekbekoe** [comment]
At this point, HTTP/2 on *.devtunnels.ms is not planned. Given this, I'll be closing this issue and if we are able to add this in the future, we'll re-open. However, thanks for your feature request for this.

**Comment by mbsysde99** [comment]
> We do not currently support HTTP/2 via `*devtunnels.ms`. However, this should be possible via the `devtunnel connect TUNNELID` command documented on this page - https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands. With this, the client can connect to your grpc server via `localhost:PORT`.
> 
> I've marked this as a feature request for support HTTP/2 on `*.devtunnels.ms` but let us know if the above works.

I tried gRPC Service with Certificate Authentication WITHOUT DevTunnel Cli (Intranet), everything works normally.

But when I used DevTunnel-Cli, it doesn't work?

What confuses me is that the DevTunnel-Cli status is connected, but the data from the gRPC Service does not appear in Client Side and I don't have any error information.

Can you share a successful test code?

Thanks,
Mbeds
