### ISSUE TITLE
Support non-debian based linux distros in install script

### ISSUE THREAD

**Issue by christianfosli** [microsoft/dev-tunnels#269]
I tried to follow the installation instructions from [Microsoft Learn](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=linux#install) on Fedora Linux:

> ```
> curl -sL https://aka.ms/DevTunnelCliInstall | bash
> ```

but the script fails with the error

```
sudo: apt-get: command not found
```

From what I can see, the install script only uses `apt-get` for installing the libsecret dependency, not for installing dev-tunnels itself.
I understand its a hassle to support all kinds of package managers on all kinds of distributions, but perhaps this script could be updated to check if `apt-get` is available, and if not the print a warning that dependencies must be installed manually?

**Comment by christianfosli** [comment]
A workaround to successfully install dev-tunnels using the convenience script on Fedora Linux is to grep out the `apt-get` lines from the script before executing it:

```patch
curl -sL https://aka.ms.DevTunnelCliInstall | grep -v apt-get | bash
```

**Comment by derekbekoe** [comment]
Thanks for the feedback. This seems like it'd be worthwhile to have. We'll take a look at improving the experience here.

**Comment by atrauzzi** [comment]
Jumping on here to say I've run into this issue.

Perhaps you can look at distributing as a flatpak, or a dotnet CLI tool?  Would love to take advantage of the Aspire integration.
