### ISSUE TITLE
Support custom names

### ISSUE THREAD

**Issue by cabal95** [microsoft/dev-tunnels#272]
I apologize in advance as this is most likely the wrong place to request this feature, but I could not find a better place for it.

It would be great to have the ability to reserve a permanent host name, especially one that is slightly friendlier when we have to tell it to somebody over the phone or type it in on a mobile device. Because of the multi-region support, this might not be possible. But I would think in most cases we'd get good enough results since I don't normally move around geographically much when testing stuff via dev tunnels.

The general reasoning is that while the 30-day persisted name is very helpful, it's not uncommon for us to work with external services (for example mailgun) in our testing. We don't need the tunnel to test with these services very often, but it's still a pain to go in and reconfigure the service for a new URL if it has been more than 30 days since we last used the tunnel. This is especially true when it's a shared service that multiple developers use. Each developer has to reconfigure the service to point to their instance instead of spinning up a tunnel with a common name available to all developers.

Bonus points would be if we could reserve an entire prefix for our name/organization.

`https://<reserved-name>.usw3.devtunnels.ms`
`https://*.<reserved-name>.usw3.devtunnels.ms`

I would be fine if `reserved-name` was something that was still assigned to use. Since we have to sign in to our MS account, if it was either our e-mail/login name or org name, that would suffice so that we can't just start gobbling up easy to type names. So:

`https://user_domain_org.usw3.devtunnels.ms`
`https://*.org-name.usw3.devtunnels.ms`

**Comment by curib** [comment]
Hi @cabal95, this is exactly the right place to request this! Thank you for taking the time to open this issue and share why you would like us to support custom names. Sounds like it would be simpler if multiple developers could use a tunnel with a common name that's available to all developers in your organization. We'll respond here once we have an update or any additional questions!

**Comment by derekbekoe** [comment]
Thanks for the feature request.
Unfortunately, we don't have plans to add support for this at this point in time.
If in the future, we are in a position to reconsider, we'll re-open this issue.
Many thanks again for the suggestion here.

**Comment by servefast-cto** [comment]
@derekbekoe i think this is one of the first features we actually need. Other things are working well but it is annoying to change urls everywhere when something is not working etc.

**Comment by derekbekoe** [comment]
While we don't support _custom_ names, we do support persistent names.
As long as the tunnel is used at least every 30d, the existing tunnel you have will remain.
@servefast-cto Are you aware of that feature?

**Comment by servefast-cto** [comment]
@derekbekoe yes i am but as i mentioned in another issue when you have a problem with tunnels i tend to delete it and run it again to see if anything changes and then i have to change all urls in the app its anoying :). I think custom names would be great we could completely delete tunnels and create new one with same custom name. Also imagine a project that is on maintenance and you are using it maybe twice a year to do minor changes

**Comment by derekbekoe** [comment]
@servefast-cto understood.
Unfortunately, we don't have plans to add support for that at this point.

**Comment by jongio** [comment]
I was looking at devtunnels as an ngrok replacement, but without static sub-domains it's a no-go because of all of the downstream effects on oauth callback url configurations.  I highly recommend implementing this feature.  It will help tremendously with adoption of devtunnels.

**Comment by Dzivo** [comment]
This should be planned just had to change 40 files where urls are used because my tunnel expired and when i rerun it i got new urls

**Comment by derekbekoe** [comment]
Thanks for the feedback and discussion so far on this thread. Today, unused tunnels will expire after 30d. In other words, if you continue to use the tunnel at least every 30d, you'll continue to have access to it. Beyond that, unfortunately at this time, we still do not have plans to support custom names or to allow unused tunnels to persist beyond 30 days of inactivity.

Given this, a workaround for tunnel expiry is to ensure that tunnel urls are not hard-coded in applications and instead can be provided via configuration or as an environment variable. This should avoid the need to change so many source code files when a tunnel expires. If using Visual Studio, this is supported natively - https://learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?view=aspnetcore-9.0#tunnel-url-environment-variables. If using VS Code or otherwise, you can set an environment variable that is set based on the response from a `devtunnel get/list` response.

I appreciate that this would not be applicable if you also have many webhooks or callbacks that may call into the tunnel. Typically for dev-test scenarios, we do not see large numbers of webhooks or callbacks being used.

Lastly, it's worth reiterating that Dev Tunnels is designed for for ad-hoc dev-test scenarios and not for production workloads. For production workloads, there are many alternatives for hosting services.

**Comment by Dzivo** [comment]
@derekbekoe What about redirect URL that we need to setup for each provider. We do that for testing and if it changes we do need to change all of that it is tiresome and not necessary. Stop and listen to the communities needs.  Your AI responses are ridiculous.

**Comment by cabal95** [comment]
@derekbekoe thanks for your response. I understand the need to keep focus on the largest user base. Even though something might be a useful feature to some, sometimes it just doesn’t fit the bigger picture. If that bigger picture and a majority of use cases start to lean towards making this feature a better fit for the product then I will be happy to see that happen. Until then I still appreciate the work you all put into this tool.

**Comment by servefast-cto** [comment]
Just seen that it is a heated debate my opinion is still that this is a must feature all of the other tunnel providers have and if it must be a Paid feature we would be happy to pay for it @cabal95 @derekbekoe

**Comment by servefast-cto** [comment]
@Dzivo actually we have the same problem in our project we have to change redirect URLS if this changes but we have a scheduled task to do this once a month where we launch it manually it is annoying but hey they have far bigger problems in MS their AD login is totally useless half the time doesn't even work we get random redirect especially when you have to switch accounts.

**Comment by pkleskovic13** [comment]
@derekbekoe @cabal95 I would like to see this feature as well
