### ISSUE TITLE
devtunnel rewrites Origin request header to localhost 

### ISSUE THREAD

**Issue by joostd** [microsoft/dev-tunnels#284]
I am running into CORS issues when connecting from a browser to a local REST API through devtunnel.
The reason seems to be that devtunnel rewrites the Origin request header to `http://localhost:nnnn` in some cases.

To reproduce, consider a PHP web application that returns the Origin request header:

```php
<?php
# file index.php
echo "Origin:" . (print_r($_SERVER['HTTP_ORIGIN'], true)) . "\n";
```

If I run this locally using PHP's built-in web server:
```bash
php -S 0:8080 index.php
```

I can use `curl` to inspect the `Origin` header received:

```bash
$ curl http://localhost:8080 -H'Origin: http://whatever.example.com'
Origin:http://whatever.example.com
```

If I start a devtunnel and use that, it works similarly:
 
```
$ curl https://abcd1234.euw.devtunnels.ms:8080 -H'Origin: http://whatever.example.com'
Origin:http://whatever.example.com
```

But if I use an origin for the devtunnel host on a different port, the Origin suddenly gets rewritten to localhost:

```
$ curl https://abcd1234.euw.devtunnels.ms:8080 -H'Origin: https://abcd1234.euw.devtunnels.ms:8081'
Origin:http://localhost:8080
```

This is causing CORS issue when I have a frontend and a backend application using the same devtunnel hostname with different ports.

**Comment by derekbekoe** [comment]
In the devtunnel CLI, you can use `devtunnel update --host-header unchanged` to keep the original header.
```
  --host-header <host-header>      Host header value to rewrite in requests 
                                   forwarded from a web client. Use "unchanged" 
                                   to keep the original header, By default Host 
                                   header is changed to "localhost".
```

Does this help?

**Comment by joostd** [comment]
Perfect - I never found those update options for some reason.

    devtunnel update --origin-header unchanged

does the trick for me. Thanks!
