### ISSUE TITLE
CORS issue when connecting to DevTunnel

### ISSUE THREAD

**Issue by mb236** [microsoft/dev-tunnels#296]
I currently have a scenario where I'm running into an issue with CORS when I try to connect from one dev tunnel to another.
In my scenario I'm hosting an Angular application on devtunnel1.devtunnels.ms and my ASP.NET Core backend on devtunnel2.devtunnels.ms. I would like to communicate my Angular application (hosted on devtunnel1) to communicate with my backend hosted on devtunnel2.

Since the HTTP requests are performed by the browser, CORS is checked an I'm receiving an error of the following kind:

Access to XMLHttpRequest at 'https://devtunnel1.devtunnels.ms' from origin 'https://devtunnel2.devtunnels.ms' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 

I should mention that the request itself is routed successfully to my backend on devtunnel2, since the response code is a 200 and I also see the request coming through. The response is blocked from the browser due to the mentioned CORS error.

Did I configure something wrong or is this scenario not supported yet?

**Comment by Plevi1337** [comment]
Were you able to solve this somehow? I'm running into the same issue.

**Comment by klvnraju** [comment]
Did you add access-control-allow-origin header for your server?

I am trying to repro this issue and these is the sample code I used for the repro and things seems to be working as expected.

Below is the server code which adds CORS header. (Update the origin to the client tunnel address and make sure this is anonymous tunnel)
``` js
const express = require('express');
const cors = require('cors');
const app = express();

const ingredients = [
    {
        "id": "1",
        "item": "Bacon"
    }
];

// Update this with client tunnel url
app.use(cors({
    origin: 'https://qjrvmwhh-5070.usw2.devtunnels.ms'
}));

app.get('/ingredients', (req, res) =>{
    res.send(ingredients);
});
app.listen(6069);
```

And below is a simple client index.html to call this api. (Update the server tunnel url)
``` html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Home</title>
        <script type="text/javascript">
            fetch("https://qp1bckqj-6069.usw2.devtunnels.ms/ingredients").then(req => req.text()).then(console.log)
        </script>
    </head>
    <body>
        <div class="container">
            <h1>Home</h1>
        </div>
    </body>
</html>
```

And note the access-control-allow-origin header that server responds with.
![image](https://github.com/microsoft/dev-tunnels/assets/25800054/41ba325f-33bb-4d48-8e4f-fbedd0376a4d)

**Comment by mb236** [comment]
Hi @klvnraju,
I double checked and it seems that was really an issue with the CORS settings on my ASP.NET Core service. 

In my case I tried to use wildcard subdomains (e.g. "https://*.devtunnels.ms") and there are two things that I was missing:

-  You need to explicitly call `SetIsOriginAllowedToAllowWildcardSubdomains()` to allow for the use of wildcard subdomains
- At the time of writing wildcard subdomains cannot contain a wildcard port. So a wildcard like this: `https://*.devtunnels.ms:*` (to allow for a random port) will resume in an error. In my case I just provided the port that I wanted to the wildcard e.g. `https://*.devtunnels.ms:4200` and than it started working.

This issue can be closed from my end as is not an issue related to Dev Tunnels. It just something to keep in mind while one is setting up CORS configuration 😄

**Comment by SaptodeepSarkar** [comment]
I have a different issue to have. I have my frontend on Netlify and my Nodjs backend on DevTunnels. I am getting a kind of same error, but the above is not the solution to my problem.

Access to fetch at 'https://9jbr54hr-8080.inc1.devtunnels.ms/api/projects' from origin 'https://website.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I would be extremely appreciative of any assistance.

`// Modules/Packages for the server
const bodyParser = require('body-parser'); // Importing bodyParser package
const express = require('express'); // Importing express package
const path = require('path'); // Importing path package
const fs = require('fs').promises; // Importing fs package
const cors = require('cors'); // Importing cors package
const { v4: uuidv4 } = require('uuid'); // Importing uuid package
const morgan = require('morgan'); // For logging requests

// Initialize Express app
const app = express();

// Pathes for Storage files
const Contactjson = path.join(__dirname, 'BackEnd', 'Contact.json');
const Projectjson = path.join(__dirname, 'BackEnd', 'Projects.json');
const Teamjson = path.join(__dirname, 'BackEnd', 'Team.json');
const Volunteerjson = path.join(__dirname, 'BackEnd', 'Volunteer.json');

// Middleware
app.use(morgan('combined')); // Log all requests
app.use(cors({
    origin: '*'
}));
app.use(express.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use('/', express.static(path.join(__dirname, 'public')));

// Start server
const PORT = 8080;
app.listen(PORT, () => {
    console.log(`Server running at http://localhost:${PORT}`);
});`
