### ISSUE TITLE
requesting increase `Max web-forwarding HTTP request body size` and `Bandwidth`

### ISSUE THREAD

**Issue by ISySRGg** [microsoft/dev-tunnels#301]
I'm developing Web UI to inference video/image based on trained Deep Learning. So the web app is using resource that related with bandwidth, transfer rate, request body size.
I need to grading the `dev tunnel`limitation with this specification:

Resource | Limit | Reason 
-- | -- | -- 
Bandwidth | 60 GB per user (upgrade) | Since many clients will hit my web, I need to upgrade it.
Tunnels | 2 per user (downgrade) | I actually just need one, the other one is just reserved purpose, so can downgrade it
Active connections | 20 per port (default) | I have no idea, so I keep it default, it seems related with TCP connection keep alive
Ports | 2 per tunnel (downgrade) | Same as tunnels reason
HTTP request rate | 6000/min per port (upgrade) | I have many PUT requests from client to update inference progress of video/image
Data transfer rate | Up to 40 MB/s per tunnel (upgrade) | My local server network has 100Mbps setup
Max web-forwarding HTTP request body size | 128 MB (upgrade) | Many videos to upload has size about it

**Comment by curib** [comment]
Hi @ISySRGg, thank you for reaching out to us, sharing your scenario, and the limits you need. Currently, we cannot support this request. I'm going to close this issue since we don't plan to support limits that high.

**Comment by curib** [comment]
Hi @ISySRGg, thank you for reaching out to us, sharing your scenario, and the limits you need. Currently, we cannot support this request. I'm going to close this issue since we don't plan to support limits that high.
