### ISSUE TITLE
Listing dev tunnels or creating a new dev tunnel takes more time than it did previously

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/dev-tunnels#315]
I've noticed that in recent days, creating a development tunnel or clicking 'Show Dev Tunnels Window' in VS is taking longer than it used to. Do you happen to know why this is happening and how I can resolve it?

And I have tried list dev tunnels in Dev Tunnel CLI, it seems to have the same problem.

**Comment by curib** [comment]
@xiaolang124, thank you for reaching out and sharing with us that creating a tunnel or clicking 'Show Dev Tunnels Window' in VS is taking longer than it used to. A fix for this is coming soon!

**Comment by curib** [comment]
@xiaolang124, this is fixed now, so I'm going to close the issue. Please reopen it if you're still experiencing the issue though. Thank you!
