### ISSUE TITLE
Rust devtunnels client can no longer parse TunnelEndpoints

### ISSUE THREAD

**Issue by connor4312** [microsoft/dev-tunnels#318]
@jfullerton44 in this change, the ID for the tunnel endpoint became mandatory

https://github.com/microsoft/dev-tunnels/blame/c85e0671d98dd25331149959af6e4adf67dfb2b8/cs/src/Contracts/TunnelEndpoint.cs#L31

However, it seems like the Dev Tunnels service does not actually return that as a non-nullable string. For example, this is my tunnel in production

```
  "endpoints": [
    {
      "hostRelayUri": "wss://usw2-data.rel.tunnels.api.visualstudio.com/api/v1/Host/Connect/29034sjz",
      "clientRelayUri": "wss://usw2-data.rel.tunnels.api.visualstudio.com/api/v1/Client/Connect/29034sjz",
      "id": null,
      "connectionMode": "TunnelRelay",
      "hostId": "706f244f-a4d3-422c-a8a4-f8dc272cb7e5",
      "portUriFormat": "https://29034sjz-{port}.usw2.devtunnels.ms/",
      "tunnelUri": "https://29034sjz.usw2.devtunnels.ms/",
      "portSshCommandFormat": "ssh 29034sjz-{port}@ssh.usw2.devtunnels.ms",
      "tunnelSshCommand": "ssh 29034sjz@ssh.usw2.devtunnels.ms"
    }
  ],
```

So, trying to parse that in Rust gives `invalid type: null`.

The generator uses the presence of the `[JsonIgnore(...)]` attribute to determine if a field should be nullable. Should that be applied to the ID?

**Comment by jfullerton44** [comment]
In future api-versions the id should always be set, but for now I get your point. I created a PR to make this property nullable which should make the changes more backwards compatible https://github.com/microsoft/dev-tunnels/pull/319

**Comment by connor4312** [comment]
Thanks!
