### ISSUE TITLE
devtunnel login fails with 403 on the localhost callback

### ISSUE THREAD

**Issue by gakama** [microsoft/dev-tunnels#330]
The console then keeps waiting.

```
Tunnel CLI version: 1.0.791+d10ee4be43

Tunnel service URI        : https://global.rel.tunnels.api.visualstudio.com/
Tunnel service version    : 1.0.944.532 (14026cffe3; 2023-10-04 01:45:30Z)
Tunnel service cluster    : usw2
```

**Comment by jramsay** [comment]
Thanks for reporting the issue @gakama!C an try updating to the [latest Tunnel CLI](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started) and let us know if you can still repro the issue?  

If so, can you try logging in as follows:

`devtunnel login -d`

This should allow you to login with a GitHub account with device code login, when the local interactive browser login isn't possible.

**Comment by derekbekoe** [comment]
Closing this as stale and we've made improvements in this area. If you feel it deserves to stay open, please clarify your use case and provide additional information. Thanks.
