### ISSUE TITLE
Run `devtunnel` in the background

### ISSUE THREAD

**Issue by Dufran** [microsoft/dev-tunnels#338]
Hi, can someone tell is there any option to launch devtunnel host 
In detached (background mode)?

**Comment by curib** [comment]
Hi @Dufran, thank you for reaching out to us! We currently do not support the option to launch `devtunnel host` in background mode. I'm going to tag this issue as a feature request and keep it open. 

We'd love to hear more from the community if this is something ya'll want. Folks, please up-vote this issue if you'd like the ability to run `devtunnels` as a service on your machine, so you can host tunnels as a background process.

**Comment by derekbekoe** [comment]
Token expirations vary. There is some documentation on this at https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/security#tunnel-access.

Unfortunately, we don't have plans to add the ability to have `devtunnel` to run in the background so I'll be closing this issue.
However, depending on exactly what you're looking to do, it may be possible to integrate with one of our SDKs. These can be found in the source code in this repo.
