### ISSUE TITLE
Request to increase Max Bandwidth 

### ISSUE THREAD

**Issue by gauravkeshre** [microsoft/dev-tunnels#339]
Hi,
I am developing Teams Platform apps with SSO in place. I need to deploy these in local for faster evaluation and register these urls  in Azure portal. 

I rely on devtunnel's fixed url to save myself from updating the azure portal app registration.

I think I have run out of my quota. I need another 6 GB quota. 

Kindly update the max bandwidth.

**Comment by curib** [comment]
Hi @gauravkeshre, thank you for reaching out and sharing your request for a higher bandwidth limit! Unfortunately, we can't support another 6 GB at this time. 

If anything changes, I'll update this issue.

**Comment by derekbekoe** [comment]
We recently increased the monthly limit to 5GB. However, we don't have plans to increase the limit beyond this point at this time.
Current limits can be found at https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#dev-tunnels-limits.
