### ISSUE TITLE
Using anonymous access devtunnel for accessing http api - authorization header sent from client is dropped

### ISSUE THREAD

**Issue by SecureFromScratch** [microsoft/dev-tunnels#356]
From within a vscode extension I issue the follwoing node-fetch request:

fetch("http://tunnel-address:80/path1/path2", {
      headers: {
        authorization: `Bearer ${token}`,
        accept: 'application/json'
      }
    });
(where "token" holds a valid token received from my api's login request.

I output all headers on server side and authorization header does not reach server.

When accessing directly without the tunnel, (i.e. url is http://localhost:9000/path1/path2) the authorization header IS recevied on the server side.

**Comment by derekbekoe** [comment]
I wasn't able to reproduce this for a tunnel-port with anonymous access enabled.
The authorization is received as expected by the server.

You mentioned `http://tunnel-address:80/path1/path2`. One change you can try is to remove `:80` and use `https://tunnel-address/path1/path2` instead.

Here's the steps I used.


**Client using node-fetch:**
```js
const fetch = require('node-fetch');

const url = 'https://tunnelid-3000.usw2.devtunnels.ms/endpoint';
const authToken = 'your-auth-token';

fetch(url, {
  headers: {
    Authorization: `Bearer ${authToken}`,
    accept: 'application/json'
  }
})
  .then(response => console.log(response))
  .then(data => {
    // Handle the response data here
    console.log(data);
  })
  .catch(error => {
    // Handle any errors that occurred during the request
    console.error(error);
  });

```


**Server-side code:**
```python
# python3 -m pip install flask
from flask import Flask, request

app = Flask(__name__)

@app.route('/endpoint', methods=['GET'])
def endpoint():
    # Get the Authorization header
    auth_header = request.headers.get('Authorization')
    # Check if the header exists and starts with 'Bearer '
    if auth_header and auth_header.startswith('Bearer '):
        # Extract the token value
        token = auth_header.split(' ')[1]
        # Print the token to the console
        print("token:", token)
        return 'Token received and processed successfully'
    else:
        return 'Invalid Authorization header', 401

if __name__ == '__main__':
    app.run(port=3000)
```

**Comment by derekbekoe** [comment]
Closing as stale.
