### ISSUE TITLE
Python version of this management sdk

### ISSUE THREAD

**Issue by stikkireddy** [microsoft/dev-tunnels#357]
Would be great if we can have an sdk to manage tunnels via python.

**Comment by derekbekoe** [comment]
Current we have no plans for a Python SDK. However, we'll keep this open and mark as a feature request.

**Comment by derekbekoe** [comment]
Unfortunately, we still don't have plans to add a Python SDK. Given this, I'll be closing this issue but thanks for the feature suggestion.

**Comment by danmarshall** [comment]
Hello, I'd like to vote to have this feature. Currently my team is trying out pyngrok. Our scenario is we run in notebooks.
