### ISSUE TITLE
Provide the API version for TS' HttpTunnelManagementClient as an enumeration

### ISSUE THREAD

**Issue by connor4312** [microsoft/dev-tunnels#361]
The valid versions of the `apiVersion` passed into the `HttpTunnelManagementClient` are checked at runtime and an error is thrown if invalid

https://github.com/microsoft/dev-tunnels/blob/2f315dc53235f691435b06faaddfa81251638bd1/ts/src/management/tunnelManagementHttpClient.ts#L142-L144

It would be less error-prone if API vesions were exposed as a type (e.g. an enum or union of string types) so that they can be checked at compile-time.

This led to some confusion in https://github.com/microsoft/vscode-remote-tunnels/pull/709#discussion_r1416362126

**Comment by derekbekoe** [comment]
@jfullerton44 can this be done?

**Comment by jfullerton44** [comment]
PR created https://github.com/microsoft/dev-tunnels/pull/373/files
