### ISSUE TITLE
devtunnel host crash with `Value cannot be null. (Parameter 'id')`

### ISSUE THREAD

**Issue by Socolin** [microsoft/dev-tunnels#367]
When trying to start my tunnel today, with `devtunnel host` I'm getting the following error:

```
Unhandled exception: System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at Microsoft.Requires.NotNullOrEmpty(String value, String parameterName)
   at Microsoft.DevTunnels.Management.TunnelManagementClient.DeleteTunnelEndpointsAsync(Tunnel tunnel, String id, TunnelRequestOptions options, CancellationToken cancellation)
   at Microsoft.DevTunnels.Cli.Commands.HostCommand.HostAsync(UInt16[] portNumbers, String protocol, String sshUser, TunnelCommandOptions options, CancellationToken cancellation) in /__w/1/s/src/Tunnel/Src/CLI/Commands/HostCommand.cs:line 267
```

```
devtunnel show 
Tunnel ID             : xxxxxx
Name                  : 
Description           : 
Labels                : some-label
Access control        : {+Anonymous [connect]}
Host connections      : 0
Client connections    : 0
Current upload rate   : 0 MB/s (limit: 20 MB/s)
Current download rate : 0 MB/s (limit: 20 MB/s)
Upload total          : 16 MB
Download total        : 226 MB
Ports                 : 1
  8084  auto  https://xxxxxx-8084.use.devtunnels.ms/  
Tunnel Expiration     : 28.7 days

```

devtunnel version
```
Tunnel CLI version: 1.0.1042+788c4fbe73

Tunnel service URI        : https://global.rel.tunnels.api.visualstudio.com/
Tunnel service version    : 1.0.1046.58452 (54e4c4e036; 2023-11-22 23:50:22Z)
Tunnel service cluster    : use
```

**Comment by jfullerton44** [comment]
@Socolin Thanks for pointing this out, I have a PR up for this now. It likely will not be released until the new year. If you continue to see the error locally, can you try running `devtunnel list` and then using `devtunnel delete` to delete all your current tunnels. Please let me know if that doesnt stop the issue

**Comment by Socolin** [comment]
I downgraded to an older version and now it works, I'll wait for the fix to be merge to upgrade.

FYI: the link this page seems to download an old version of devtunnel https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=linux#install the script download the latest one

**Comment by eternalphane** [comment]
> I downgraded to an older version and now it works.
how did you download old versions of devtunnel? I can't find any documentation for it

**Comment by Socolin** [comment]
After checking it seems good, I download the latest version on https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=linux#install I don't know why I got an older one last time, probably some cache somewhere

**Comment by jfullerton44** [comment]
> > I downgraded to an older version and now it works.
> 
> how did you download old versions of devtunnel? I can't find any documentation for it

@eternalphane We don't support downloading older versions, all download links should point to the latest release
