### ISSUE TITLE
how to get TUNNELS_TOKEN 

### ISSUE THREAD

**Issue by imblowsnow** [microsoft/dev-tunnels#376]
how to get TUNNELS_TOKEN / GitHub user authentication

**Comment by derekbekoe** [comment]
Can you share more details on what you're trying to achieve?

**Comment by imblowsnow** [comment]
I can only get GitHub user authentication through `devtunnel user show-v` now. Can I authorize it in other ways?

**Comment by derekbekoe** [comment]
Apologies for the delayed response.

We have some documentation on tunnel access tokens at https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/security#tunnel-access and https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/cli-commands#advanced-manage-dev-tunnel-access.

If that doesn't help, please comment and we can re-open the issue.
