### ISSUE TITLE
basic sample not working

### ISSUE THREAD

**Issue by mahija28** [microsoft/dev-tunnels#397]
following instructions written here: https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows

![image](https://github.com/microsoft/dev-tunnels/assets/7418480/432423c6-200d-4987-99ef-8ad3ce8602cf)

error: ClientSSH: PortForwardingService connection  to localhost:8080 failed: No connection could be made because the target machine actively refused it.
are there firewalls/other settings that need to be removed/installed to get dev tunnel working?

**Comment by derekbekoe** [comment]
Are you hosting anything on port 8080? It's not clear from the screenshot.
If so and it still doesn't work, there may be some firewall/network configurations interfering here.
