### ISSUE TITLE
Edit and Resend Issues

### ISSUE THREAD

**Issue by david-maw** [microsoft/dev-tunnels#401]
I've seen two problems so far

1) Sometimes it simply does not work, the Network Console  window opens up but attempting to resend from it fails and from then on if you close the window and try again it shows no data.
2) If it is working resending a message picks up a lot of new headers (presumably from the page context). This is not helpful if you're just trying to resend the original message.

**Comment by derekbekoe** [comment]
Edit and Resend via the tunnel inspection page is not a feature we specifically supported so you mileage may vary with it.
I've marked this as a feature request but given we don't have plans to look at this in the short or medium term, I'm going to close this issue. If we decide to revisit this, we'll re-open this issue.

**Comment by david-maw** [comment]
OK, thanks @derekbekoe, I can get around the resend limitation by using ngrok for development or testing that needs resend.

The non-working issue is different, and I assume it is likely to be resolved in due course but at present it's a showstopper - do you want me to submit it as a separate issue?

**Comment by derekbekoe** [comment]
> The non-working issue is different, and I assume it is likely to be resolved in due course but at present it's a showstopper - do you want me to submit it as a separate issue?

The "Edit and Resend" UI option you see is not something we specifically integrated into dev tunnels (instead, it came with browser devtools UI and we didn't remove that menu option). As such, we wouldn't expect it to work. So, it'd be a feature request for us to support "Edit and Resend" and unfortunately we don't have plans to add support for it at this time.

Hope that helps clarify.

**Comment by david-maw** [comment]
Thanks @derekbekoe, that's what I understood from your first comment. I realize that resend is not one of the requirements for the dev tunnels feature so I'll need to use something else to satisfy that requirement when it arises, Please just take this as a vote for a new feature.
