### ISSUE TITLE
Bandwidth increase request

### ISSUE THREAD

**Issue by fazeel15** [microsoft/dev-tunnels#402]
I am currently working as an AI Researcher at Khyber Medical University. To connect to my workstation, I use Devtunnel. However, I have run out of my data limit. My account is linked with Microsoft via the email [fazeelkhan15@hotmail.com](url).

I kindly request an increase in my bandwidth to 10 GB.
```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [x] Additional Bandwidth request.
```

**Comment by derekbekoe** [comment]
`devtunnel limits` should list when your limit will next be reset.
The current limits are documented at https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#dev-tunnels-limits.

Can you share more about how you're using dev tunnels and how you were able to hit the data limit?

**Comment by derekbekoe** [comment]
Closing for now as we haven't heard back. Hopefully the information shared above should help.

**Comment by fazeel15** [comment]
Dear @derekbekoe ,
Apologies for the delay in the reply; I missed the earlier notification.

My use case scenario is as follows: I host ports from 8888 to 8898 for Jupyter Notebook, and also host ports from 6006 to 6016 for TensorBoard. Additionally, I have RDP on port 3389 and SSH on port 22. I use Jupyter for coding and data transfer, mainly for code files and plots. TensorBoard is utilized for monitoring and visualizing the training process. RDP is used for navigating through files and resolving any issues that occur.

I am not sure about what is the main reason for reaching the limit.

**Comment by derekbekoe** [comment]
I highly suspect the high bandwidth use is either due to the data transfer in Jupyter or due to the use of RDP.
Unfortunately, we don't have plans to increase the limits beyond what's currently available and documented.

To determine which component is using the most bandwidth, you could run each component on a separate tunnel and compare the bandwidth used via the `devtunnel show` command.

**Comment by fazeel15** [comment]
Ok thanks.
