### ISSUE TITLE
Include port forwarding URIs in "devtunnel show" even when not hosting

### ISSUE THREAD

**Issue by Socolin** [microsoft/dev-tunnels#408]
With latest version the url is not print anymore after the port in `devtunnel show` output and with the new human readable id, the url does not seems to match the new id.

I need to know this info before running withtou running `devtunnel host` the tunnel is active in another terminal and I cannot run the commande or it will kill it.

Is the new id style also bind to a url ? Is it safe to depend on it now ? or could you just display the url again in the `devtunnel show`

**Comment by Socolin** [comment]
It's not the easiest way to get it but it should works. Thanks.

Since this seems to be the HTTP response from the server, could this changes or can I rely on this info being here in the future ?

Also I'm wondering if there is any plan to have kind of a `--json` option that would make using the CLI from scripts much easier.

**Comment by derekbekoe** [comment]
The latest versions of the CLI support `devtunnel show --json`.
Updated the issue title to reflect the feature request.

We'll take a look into supporting this and including it in the `--json` output also.

**Comment by Socolin** [comment]
Ho nice.

I just checked and with the `--json` the url seems to be present in `tunnel.ports[].portUri` so I think that all I need.

**Comment by derekbekoe** [comment]
Closing this as resolved.
