### ISSUE TITLE
Provide documentation/examples on how to use SDK in-process

### ISSUE THREAD

**Issue by cmenzi** [microsoft/dev-tunnels#414]
Are there any examples or documentation on how to use this SDK for example in AspNetCore integration tests.

We would like to create automated E2E integration tests inside CI/CD, which would include Azure EventGrid topics with WebHook subscribers.

Therefore, I see this SDK as a perfect solution. 

Scenario;
1. Spin up local http listener in test setup (eg. local port 8080)
2. Create dev-tunnel host on port 8080 and get the https url (Must be 443 and have a valid cert)
3. Register webhook subscriber on the event grid topic with the url from step 2.
4. Publish a CloudEvent to Event Grid topic
5. Verify CloudEvent is sent to the HttpListener from step 1.

What do you think?

**Comment by derekbekoe** [comment]
Hi - The scenario does seem like a good use-case for the SDK.
At this time, we don't have any documented examples. However, you could first start with reviewing the test-cases which simulate similar scenarios - https://github.com/microsoft/dev-tunnels/blob/main/cs/test/TunnelsSDK.Test/TunnelHostAndClientTests.cs#L1484.

Beyond that, we'd be happy to answer any specific questions you have on use of the C# SDK.

**Comment by cmenzi** [comment]
Thank you @derekbekoe 

I achieved it already in the meantime. :-) And I have running code available., that I would be happy to share, if you like.

**Comment by derekbekoe** [comment]
Glad you were able to find a solution and there's no need to share the code.
I'll be closing this issue now. Thanks!
