### ISSUE TITLE
Azure function support

### ISSUE THREAD

**Issue by bzuidgeest** [microsoft/dev-tunnels#422]
Azure functions are basically Websites, Why is the tooling (debug menu UI) not available on azure function projects? Would be of so much use there.

**Comment by derekbekoe** [comment]
Can you share more on the scenarios where you believe this would be useful?

**Comment by fowl2** [comment]
DevTunnels appears for me for an Azure Functions v1 SDK style project. After manually configuring the port number it seems to work fine. Some automation there to hook it all up would be nice.

It's useful for eg. testing webhooks.

**Comment by derekbekoe** [comment]
Thanks for the feedback. At this time, we don't plan on changing the experience here. However, the tunnel can manually be created in VS and also via the `devtunnel` CLI.
