### ISSUE TITLE
No dev_tunnel_url in teamsapp.local.yml

### ISSUE THREAD

**Issue by mclearyKA** [microsoft/dev-tunnels#426]
I'm trying to automate sending teams messages. 

I'm following a [tutorial ](https://www.youtube.com/watch?v=YeGRgScvil8) on creating a teams app message extension, but there's something wrong with the dev tunnel.  When I follow the instructions, On step 2 I get the following error:

No DEV_TUNNEL_URL in 'teamsapp.local.yml'. Create a new public dev tunnel in the debug dropdown menu (Dev Tunnels), or select an existing one. Alternatively, you can fill in the DEV_TUNNEL_URL field in the 'teamsapp.local.yml' file

I'm not sure where to get the url from to fill in.

This is the GettingStarted.md instructions:
In the debug dropdown menu, select `Dev Tunnels > Create a Tunnel` (set authentication type to Public) or select an existing public dev tunnel.
2. Right-click your project and select `Teams Toolkit > Prepare Teams App Dependencies`.
3. If prompted, sign in with a Microsoft 365 account for the Teams organization you want to install the app to.
4. Press F5, or select the `Debug > Start Debugging` menu in Visual Studio
5. When Teams launches in the browser, you can navigate to a chat message and [trigger your search commands from compose message area](https://learn.microsoft.com/microsoftteams/platform/messaging-extensions/what-are-messaging-extensions?tabs=dotnet#search-commands).

I didn't have dev tunnels in my debug dropdown menu (like the video shows around 6:30-9:30) and I'm not sure how to add it.  I tried to right click the dropdown menu, customize, and checked dev tunnels and closed it but it didn't change the error.

I tried removing the extra dev tunnels that I created in my list but get an error :
Failed to delete the dev tunnel. The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch.

I'm not sure what is causing this. 

This is what my tunnels look like that I created thru vs2022, view dropdown, Other Windows, dev tunnels. 
![image](https://github.com/microsoft/dev-tunnels/assets/111789999/533eed2b-d715-4367-87e4-584bab1d9b1e)

Here's one example I was looking at too. 
https://devblogs.microsoft.com/microsoft365dev/post-notifications-to-microsoft-teams-with-net-using-teams-toolkit-for-visual-studio/
It's referring to use ngrok but I don't think it's safe to allow ingress into my application. I'm not sure if this is a step I'm missing...it wasn't referred to in the video but they just glossed over the dev tunnel part.

 I saw this example, but I'm not sure where they get the url from to use
https://github.com/microsoft/dev-tunnels/issues/346

**Comment by derekbekoe** [comment]
> I didn't have dev tunnels in my debug dropdown menu (like the video shows around 6:30-9:30) and I'm not sure how to add it.

Is your project an ASP.NET Core project? This _may_ be the reason why it's not showing up - https://learn.microsoft.com/en-us/aspnet/core/test/dev-tunnels?view=aspnetcore-8.0#prerequisites.

> Failed to delete the dev tunnel. The SSL connection could not be established, see inner exception. The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch.

This error sometimes indicates that there's a proxy that's preventing Dev Tunnels from connecting. If you're in an organization, consider checking with network administrators if there's such a restriction in place.

**Comment by derekbekoe** [comment]
Closing as stale.
