### ISSUE TITLE
Feature request: Ability to extend gateway timeout to devtunnel

### ISSUE THREAD

**Issue by dsmaher** [microsoft/dev-tunnels#427]
I have an API call that, due to downstream services, takes more than 3.5 minutes to return.  While using devtunnels, it always returns a `504 Gateway Timeout` when calling this API.

In addition, sometimes while tracing through code on other APIs that take less time, the client will get a `504` and I'm unable to continue tracing the scenario.

In some cases, I can use a client that supports local networking, but that's not always possible.

**Comment by derekbekoe** [comment]
Thanks for the feedback. At this time, we don't plan to add support for this. If we revisit this in the future, we'll re-open this issue.
