### ISSUE TITLE
TCP forwarding: Some HTTP requests time out

### ISSUE THREAD

**Issue by ElDavoo** [microsoft/dev-tunnels#429]
Hello,
I'm experiencing a bug similar to #276  
Context:  
- remote machine, everyone running Linux and VS code, dev tunnels and a flask app with uwsgi in Docker (compose). I run `docker compose up` from a VS code terminal.  
- The extension (automatically) forwards 127.0.0.1:5000 using `/usr/bin/docker-proxy -proto tcp etc etc`
- there is about an about 20% chance that the HTTP request just hangs (and after 100 seconds it will time out with a 504).  As a result, the page does not load and the tunnel is unusable.  
- With an SSH tunnel, nothing is done automatically: I manually forward the port, docker-proxy does not get used, and **everything works fine.**  (in that case, it gets tunneled to localhost, not to microsoft's servers.)  
- code-tunnel is installed as a persistent service  

**Code version**
1.87.2
863d2581ecda6849923a2118d93a088b0745d9d6
x64

**Some screenshots**
![20240326_14h12m20s_grim](https://github.com/microsoft/dev-tunnels/assets/7345120/7ef1afd7-2f9b-4876-9599-dc54401f4085)

**Some logs**
```
debug [russh::server::encrypted] request: Ok("ssh-userauth")
debug [russh::server::encrypted] name: "tunnel" Ok("ssh-connection") Ok("none")
debug [tunnels::connections::relay_tunnel_host] host relay client session successfully authed
debug [tunnels::connections::relay_tunnel_host] Forwarded connection to port 5000
debug [tunnels::connections::relay_tunnel_host] EOF from TCP stream, ending  
```

Is there something like a limit of concurrent connections? From the logs it looks like for every HTTP connection an SSH tunnel is made and maybe some limits get hit.  

Thank you for any attention

**Comment by ElDavoo** [comment]
vssaas-request-id : c2277c34-54cf-47fe-9377-4b7833181ebf

**Comment by ElDavoo** [comment]
hmmm, i tried the **devtunnel** CLI and it works, so where is the problem? VS code "remote" extension?

**Comment by derekbekoe** [comment]
@connor4312 is there anything that stands out here in relation to VS Code remote?

**Comment by derekbekoe** [comment]
Closing this as stale and as a workaround of using the devtunnel CLI is available. Also, VS Code has made improvements since this issue was filed that may have helped here also. Thank you.
