### ISSUE TITLE
What is the source code in this repo for?

### ISSUE THREAD

**Issue by DomenPigeon** [microsoft/dev-tunnels#432]
Hello,
I have used dev tunnel for some time now and I really think they are great. Now I was thinking about a little more advanced scenario how to use them and I read the whole docs again and just could really figure out what the C# code in this repository is for.

I have used the CLI and I know how to use it, I checked and saw that this repo doesn't contain the CLI code, so I thought that it maybe containes code how to setup your own Tunnel Relay Service in order to host your own tunnels on a server, but because there is nothing metioned about this in docs I thought it's not this.

Is it maybe to connecte to DevTunnels via code instead of via the CLI exe?

I am sorry if it's a stupid question, but I coudn't figure it out.

**Comment by derekbekoe** [comment]
This repo contains SDKs that can be used to interact with the Dev Tunnels service (e.g. manage tunnels, host tunnels, connect to tunnels, etc.).
The source code for the devtunnel CLI is not open-source. However, the CLI is built on the SDK available in this repo.

**Comment by DomenPigeon** [comment]
Oh great, so if I understand correctly if I have my own server I could use this SDK for my own hosting of dev tunnels instead of them going to azure? I could create tunnels like: https://<tunnel_id>.my-own-domain.com:8080
Is there any documentation how to do this except the source code?

**Comment by derekbekoe** [comment]
The SDK is for connecting with and using the service hosted at devtunnels.ms. We don't support running the service on your own servers.

**Comment by DomenPigeon** [comment]
Thanks for clarification.
