### ISSUE TITLE
Error, The Android emulator is unable to open the web of devtunnel,

### ISSUE THREAD

**Issue by yajiegithub** [microsoft/dev-tunnels#434]
The Android emulator is unable to open the web of devtunnel,
But Android WSL can open the web of devtunne,
I don't know where the problem is, but other websites can be opened

**Comment by derekbekoe** [comment]
We'd need more information to better help here.
From what you describe so far, I don't see any particular reason for why the devtunnel URL would not work from the Android emulator.

**Comment by yajiegithub** [comment]
> We'd need more information to better help here. From what you describe so far, I don't see any particular reason for why the devtunnel URL would not work from the Android emulator.

How should I check?
I am from China, and I guess there is a problem with DNS,
I tried the Visual Studio parameter '- dns server x.x.x.x'
But the simulator did not accept this parameter
Strangely, Android WSL For Windows does not require any operation and can directly access devtunnel

**Comment by yajiegithub** [comment]
> For example:
> 
> * What is the error you are seeing? Is it a specific HTTP status code?
> * Does the tunnel have anonymous access enabled or does it require logging in before accessing the tunnel?
> * Do you have any request IDs returned from the tunnels service?

I found the reason
Chinese government Block devtunnel,  🤣
this is a Highly regulated countries，
Any domain name needs to be on the whitelist

**Comment by derekbekoe** [comment]
Closing this as stale and as it's currently not actionable by the team.
