### ISSUE TITLE
Connection link browser fails with HTTP 431 when signing in with corporate Entra ID account 

### ISSUE THREAD

**Issue by Chida82** [microsoft/dev-tunnels#435]
When I attempt to use the tunnel link with “devttunnel”, I encounter an issue. Despite granting access solely to my colleagues within my tenant “Entra Id”, I receive a 431 error. This error also occurs for me.

![image](https://github.com/microsoft/dev-tunnels/assets/6495665/976e652e-dc3e-47c2-85b7-37bf48c934a3)

the error is after redirect

![image](https://github.com/microsoft/dev-tunnels/assets/6495665/7f58c9ed-33aa-4f2b-9501-7dcf4ae71488)

**Comment by derekbekoe** [comment]
Closing this in favor of https://github.com/microsoft/dev-tunnels/issues/425 at it's the same underlying issue.
