### ISSUE TITLE
Tunnel service returned status code: 403 Forbidden

### ISSUE THREAD

**Issue by XiaofuHuang** [microsoft/dev-tunnels#436]
Copied bug from: https://github.com/OfficeDev/TeamsFx/issues/11275
**Problem**
When attempting to create a dev tunnel using both the Dev tunnel JS SDK and CLI, user consistently encounter a 403 Forbidden error.

**Details from original post:**
I am unable to run the debug operation in Teams toolkit. I have create a testing account for running debug code. The account has custom app upload capability. But im getting this error constantly. It has only started recently, I had tried the same a month back and it was working fine.

Summary:

(×) Error: Unable to execute dev tunnel operation 'create'. Tunnel service returned status code: 403 Forbidden

Visit https://aka.ms/teamsfx-local-tunnel-task to learn more about 'Start local tunnel' task.

[2024-04-03T06:38:17.984Z] [Error] - code:Ext.DevTunnelOperationError, message: Unable to execute dev tunnel operation 'create'. Tunnel service returned status code: 403 Forbidden
Help link: https://aka.ms/teamsfx-local-tunnel-task

**Updates**
Yes, the issue is happenning even after using the dev tunnel. Still getting the same error message.
![image](https://github.com/microsoft/dev-tunnels/assets/49138419/88e9696a-6836-4255-b3c1-642300103edb)

**Comment by derekbekoe** [comment]
Do you have a request id / tunnel id with a timestamp of the request?

**Comment by ashlytom** [comment]
@derekbekoe 
I have the tunnel id. But there is no timestamp. These are the results from the verbose statement. Please let me know if more data is needed.

HTTP: GET https://global.rel.tunnels.api.visualstudio.com/userlimits?api-version=2023-09-27-preview
HTTP: Authorization: Bearer <token>
HTTP: User-Agent: Dev-Tunnels-Service-CLI/1.0.1249+67b1cd300c
HTTP: User-Agent: (OS:Microsoft Windows 10.0.19045)
HTTP: User-Agent: Dev-Tunnels-Service-CSharp-SDK/1.1.29+db5d357e46
HTTP: PUT https://global.rel.tunnels.api.visualstudio.com/tunnels/tidy-fog-26xc4x3?includePorts=true&tokenScopes=host,connect&api-version=2023-09-27-preview
HTTP: Authorization: Bearer <token>
HTTP: If-None-Match: *
HTTP: User-Agent: Dev-Tunnels-Service-CLI/1.0.1249+67b1cd300c
HTTP: User-Agent: (OS:Microsoft Windows 10.0.19045)
HTTP: User-Agent: Dev-Tunnels-Service-CSharp-SDK/1.1.29+db5d357e46
HTTP: {
  "tunnelId": "tidy-fog-26xc4x3",
  "accessControl": {
    "entries": [
      {
        "type": "Anonymous",
        "subjects": [],
        "scopes": [
          "connect"
        ]
      }
    ]
  },
  "ports": [
    {
      "portNumber": 3978,
      "protocol": "http",
      "options": {},
      "sshUser": "",
      "portForwardingUris": null,
      "inspectionUri": null
    }
  ]
}
HTTP: 403 Forbidden (307 ms)
HTTP: Server: Zscaler/6.2
HTTP: Cache-Control: no-cache
HTTP: Access-Control-Allow-Origin: *
HTTP: 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
<head>

**Comment by derekbekoe** [comment]
The error is not being returned by the Dev Tunnels service.
It appears the 403 error is coming from a proxy, Zscaler.
Please check with your network admins.
