### ISSUE TITLE
command with devtunnel full path  will have error

### ISSUE THREAD

**Issue by ayachensiyuan** [microsoft/dev-tunnels#438]
devtunnel version: 1.0.1284+d45d2345c4

<img width="674" alt="image" src="https://github.com/microsoft/dev-tunnels/assets/67082457/707683cc-1fa0-4469-9a87-c304af7f456f">

**Comment by vokom** [comment]
Having the same issue after updating devtunnels to the latest version on Linux today

**Comment by vokom** [comment]
Is there a way to rollback to the previous version of devtunnel cli for linux?

**Comment by vokom** [comment]
I rolled it back by manually downloading previous version from
https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1249+67b1cd300c/linux-x64-devtunnel
and then replacing the binary

**Comment by derekbekoe** [comment]
We're taking a look into this.

**Comment by jramsay** [comment]
@ayachensiyuan , @vokom , @markwalsh-liverpool : thanks for flagging this! The latest release (1.0.1290+8d780f0d7b) should resolve the issue.

**Comment by ayachensiyuan** [comment]
macOS still have this issue, Please fix it, thank you.

**Comment by dgmjr** [comment]
Me too!  Now I'm wishing I didn't upgrade this morning because I can't figure out how to rollback!! 😟

**Comment by bak1an** [comment]
@jramsay Somehow https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1290+8d780f0d7b/osx-x64-devtunnel-zip (which is what homebrew [downloads](https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/d/devtunnel.rb)) still contains `1.0.1287+aefc2476d4` version, which is broken:

```
$ wget https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1290+8d780f0d7b/osx-x64-devtunnel-zip 
--2024-04-28 14:34:15--  https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1290+8d780f0d7b/osx-x64-devtunnel-zip
Resolving tunnelsassetsprod.blob.core.windows.net (tunnelsassetsprod.blob.core.windows.net)... 20.150.78.164, 20.150.78.36, 20.150.78.100
Connecting to tunnelsassetsprod.blob.core.windows.net (tunnelsassetsprod.blob.core.windows.net)|20.150.78.164|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7875508 (7.5M) [application/zip]
Saving to: ‘osx-x64-devtunnel-zip’

osx-x64-devtunnel-zip                                          100%[====================================================================================================================================================>]   7.51M   443KB/s    in 22s

2024-04-28 14:34:39 (344 KB/s) - ‘osx-x64-devtunnel-zip’ saved [7875508/7875508]

$ unzip osx-x64-devtunnel-zip   
Archive:  osx-x64-devtunnel-zip
  inflating: devtunnel

$ ./devtunnel --version    
1.0.1287+aefc2476d4

$ ./devtunnel list   
Tunnel service response deserialization error: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.DevTunnels.Contracts.TunnelListByRegionResponse'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Request ID: 27d09164-5ab6-4a0c-adbc-2c6b6aead52d
```

Is there any way to download actual `1.0.1290+8d780f0d7b` somewhere?

**Comment by derekbekoe** [comment]
Until we resolve the issue with the latest versions, for now, on macOS, you can revert to the previous known good version via https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1249+67b1cd300c/osx-x64-devtunnel-zip

**Comment by clemlesne** [comment]
I confirm it does work with the build [1.0.1249+67b1cd300c](https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1249+67b1cd300c/osx-x64-devtunnel-zip).

**Comment by jramsay** [comment]
@clemlesne, @bak1an, @ayachensiyuan, @dgmjr: thanks for letting us know that there was an issue with macOS release!  The latest release on Homebrew (1.0.1293+4a61ac5730) should resolve the issue.

**Comment by bak1an** [comment]
It works, thanks!
