### ISSUE TITLE
Deserialization error, any command forms the CLI now crash

### ISSUE THREAD

**Issue by clemlesne** [microsoft/dev-tunnels#439]
## Impact

Any command forms the CLI now crash. Includes `devtunnel list`, `devtunnel show`, and `devtunnel create`.

## Short error

`devtunnel list` and `devtunnel show`:

`Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.DevTunnels.Contracts.TunnelListByRegionResponse'.`

`devtunnel create`:

```
Object reference not set to an instance of an object.
```

## Full logs

`devtunnel list` and `devtunnel show`:

```log
❯ devtunnel list --verbose
Tunnel service response deserialization error: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Microsoft.DevTunnels.Contracts.TunnelListByRegionResponse'. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Request ID: xxx
```

`devtunnel create`:

```
❯ devtunnel create claim-ai-clemsmacbook --allow-anonymous --expiration 7d
Object reference not set to an instance of an object.
```

## Versions

- Dev Tunnels: 1.0.1287+aefc2476d4
- OS: macOS 14.4.1

**Comment by derekbekoe** [comment]
Apologies for the issue. Please see https://github.com/microsoft/dev-tunnels/issues/438#issuecomment-2080242757. Updating to the latest version should resolve your issue.

**Comment by bak1an** [comment]
@derekbekoe No way to update currently, https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1290+8d780f0d7b/osx-x64-devtunnel-zip  still contains the same `1.0.1287+aefc2476d4` inside of it

**Comment by derekbekoe** [comment]
Until we resolve the issue with the latest versions, for now, on macOS, you can revert to the previous known good version via https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1249+67b1cd300c/osx-x64-devtunnel-zip

**Comment by derekbekoe** [comment]
Closing as resolved - https://github.com/microsoft/dev-tunnels/issues/438#issuecomment-2084318460
