### ISSUE TITLE
Feature Request: Configure dev tunnels trough config file 

### ISSUE THREAD

**Issue by servefast-cto** [microsoft/dev-tunnels#445]
It would be nice if we could have a file where we define our tunnels to simplify setup and running them in dev environments

**Comment by derekbekoe** [comment]
Thanks for taking the time to file this issue. Unfortunately, we’re not able to prioritize this feature request over the other higher-impact issues we receive every week, based on the votes and comments from others in the community.

**Comment by servefast-cto** [comment]
You probably have a lot of work but this would be really a neat feature worth considering for the future
