### ISSUE TITLE
Add support for GCCH tenants

### ISSUE THREAD

**Issue by JoeAlanis** [microsoft/dev-tunnels#448]
Hello, 

GCCH uses a different login url  (https://login.microsoftonline.us) which is different from the commericial login url (https://login.microsoftonline.com). Would it be possible to add a flag to toggle the login url?

https://github.com/microsoft/dev-tunnels/blob/d789eb9ce76c4318933320d7acda3cb8fba17e61/rs/src/management/http_client.rs#L721

**Comment by derekbekoe** [comment]
Hi - Thanks for reaching out.
Unfortunately, we don't support GCCH and don't have plans to support it in the near future.
I'm going to mark this as a feature request.

**Comment by derekbekoe** [comment]
Thanks for taking the time to file this issue. Unfortunately, we’re not able to prioritize this feature request over the other higher-impact issues we receive every week, based on the votes and comments from others in the community.

**Comment by ewingnoah** [comment]
@derekbekoe has there been any change to plans to provide a GCCH GitHub offering?
