### ISSUE TITLE
App occasionally goes to the wrong port

### ISSUE THREAD

**Issue by kourylape** [microsoft/dev-tunnels#449]
We have 4 main services we're forwarding:
- Ruby on Rails Backend on 9000
- React SPA on 8080
- CloudBeaver DB Client on 8978
- GraphQL on 5000

The rails app runs on port 9000, and I've seen situations where loading a page will render a 404 from another app. 

For example, http://blub-9000.use.devtunnels.ms/login should be a SSR login. Occasionally, when loading that page it will show the 404 page from CloudBeaver (8978) and the SPA (8080). The URL always remains http://blub-9000.use.devtunnels.ms/login in the browser so it's not a redirect or anything. It will randomly happen on any page at anytime, just was using `/login` as an example. 

I've confirmed using https://blub-9000-inspect.use.devtunnels.ms that the request headers remain the same even during the 404s. Just the responses differ. 

Edit: When using localhost:9000/login, we've never seen any these 404s.

**Comment by derekbekoe** [comment]
We’ve made improvements in this area since this issue was filed. We believe this may have improved your experience and are closing this issue. If this issue still persists for you, please comment on the issue and let us know. Thank you.
