### ISSUE TITLE
SSH user name is required for a port with SSH protocol.

### ISSUE THREAD

**Issue by SoftwareIncubatorSI** [microsoft/dev-tunnels#455]
Used:
   devtunnel port create --protocol ssh --port-number 22 <tunnel-id>
Tunnel service error: Invalid arguments. SSH user name is required for a port with SSH protocol.

no documentation contains for ssh

**Comment by derekbekoe** [comment]
Today, the list of supported options for Tunnel port protocol are `'http', 'https', or 'auto' (default)`.
`--protocol ssh --port-number 22` is not supported.
