### ISSUE TITLE
Google emulator rediect with url login failing 9/10 times when going trough tunnel 

### ISSUE THREAD

**Issue by servefast-cto** [microsoft/dev-tunnels#456]
https://xxxxxx-9099.euw.devtunnels.ms/emulator/auth/iframe?apiKey=myApiKey&appName=%5BDEFAULT%5D&v=10.8.0&eid=p&usegapi=1&jsh=m%3B%2F_%2Fscs%2Fabc-static%2F_%2Fjs%2Fk%3Dgapi.lb.en.6jI6mC1Equ4.O%2Fam%3DAAAQ%2Fd%3D1%2Frs%3DAHpOoo-79kMK-M6Si-J0E_6fI_9RBHBrwQ%2Fm%3D__features__#id=I0_1718635771532&_gfid=I0_1718635771532&parent=https%3A%2F%2FXXXXXX-5000.euw.devtunnels.ms&pfname=&rpctoken=58075787

This fails 9/10 times when i am using tunnel 

With: Failed to load resource: the server responded with a status of 400 ()

How can i help you to debug this ? It is vital for our application since this request is part of the login process 

EDIT: i must add that we use tunnels in development not production

**Comment by derekbekoe** [comment]
Apologies for the delay here. If this is still relevant for you, can you share the timestamp and request id (`vssaas-request-id`) for the requests that fail. This would allow us to look at our logs for those requests.

I'm closing this for now but if we get a response, we can re-open this issue.

**Comment by servefast-cto** [comment]
How can i get vssaas-request-id

**Comment by derekbekoe** [comment]
It is a HTTP header in the response on the request to `https://*.devtunnels.ms/`.

**Comment by derekbekoe** [comment]
Closing this as stale but if it's still an issue, let us know.
