### ISSUE TITLE
Can a request returning a file cause issues?

### ISSUE THREAD

**Issue by bptouchette** [microsoft/dev-tunnels#458]
I have an API where if I call a specific URI it will return a file that my browser can download.
If I use the URI with "localhost:8080" for exemple, the URI works fine and the browser downloads the file.
If I use the devtunnel uri "test-8080.use.devtunnels.ms" for exemple, then I get a 502 error everytime and nothing happens.

I can see on my server that the call is being made properly and that my server returns a 200 with the file in question but for some reason the devtunnel is returning a 502.

Is devtunnel able to support request where the response has a content-type specific to a file? Exemple image/png or application/pdf?
It seems to work fine if the response contains JSON.

**Comment by derekbekoe** [comment]
I'd recommend reviewing these limits - https://aka.ms/devtunnels/limits.
If you don't believe you're hitting any of those limits, with the request id and timestamp, we may be able to better track down the cause of the 502.

**Comment by derekbekoe** [comment]
Closing this as stale but please comment to clarify your use case if you continue to see an issue.
