### ISSUE TITLE
Force authentication

### ISSUE THREAD

**Issue by mikeblakeuk** [microsoft/dev-tunnels#459]
Can we prevent `--allow-anonymous`. 
We can't use dev tunnels because we cannot have unauthenticated traffic coming in through the firewall.

**Comment by derekbekoe** [comment]
Group Policies can be used for this on Windows devices - https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/policies

**Comment by derekbekoe** [comment]
Closing this as stale but please comment to clarify your use case if you continue to see an issue.
