### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by smbabaz** [microsoft/dev-tunnels#464]
I'm logged in to devtunnel and when I try to execute the following I receive "Object reference not set to an instance of an object."  This has worked in the past.

.\devtunnel.exe host -p 58888 -a

Any suggestions would be appreciated.

Thanks

**Comment by derekbekoe** [comment]
Which version of the CLI are you running?
This can be displayed with `.\devtunnel.exe --version`.

**Comment by derekbekoe** [comment]
Closing as this appears a duplicate of https://github.com/microsoft/dev-tunnels/issues/439
