### ISSUE TITLE
Non-Interactive Login

### ISSUE THREAD

**Issue by yassersouri** [microsoft/dev-tunnels#467]
Is there a way to login non-interactively?

Let's say I want to create a script the hosts an endpoint automatically and I don't want to do the login manually?

**Comment by derekbekoe** [comment]
It's possible to log in non-interactively.
You can run `devtunnel user login -h` to see all the available options.
In addition, this video covers the topic - https://www.youtube.com/watch?v=yCYLurylgj8.

**Comment by derekbekoe** [comment]
Closing as there are non-interactive ways to log in.
