### ISSUE TITLE
Not able to load tunnel url as iframe src

### ISSUE THREAD

**Issue by mPaella** [microsoft/dev-tunnels#468]
when using the tunnel url as the src of an iframe, i get the following error `Refused to frame 'https://github.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".`

repro:
```html
<iframe src="https://<YOUR_TUNNEL_URL>" />
```

**Comment by derekbekoe** [comment]
It appears the iframe is attempting to load the GitHub login page.
Switching the tunnel port to allow anonymous access should resolve the issue.
If not, feel free to let us know.

**Comment by derekbekoe** [comment]
Closing as this is by-design.
