### ISSUE TITLE
Is DevTunnel Cli support for Grpc or CoreWCF

### ISSUE THREAD

**Issue by mbsysde99** [microsoft/dev-tunnels#481]
Hii,

I tried run gRPC Service with Certificate authentication in an Intranet (local network). 
Everything works fine, I can connect gRPC Client to gRPC Service to get all data.

I want the gRPC Service to be accessible via the Internet from Client.
I tried running DevTunnel CLI on the Service then create a connection from the Client, and the result is  connected.

After DevTunnel CLIi is connected then I run gRPC Service.
I try to read data from the Client via the internet, there are no error messages and the data never appears.

Does DevTunnel CLI support for gRPC?

Thanks,
Mbeds

**Comment by derekbekoe** [comment]
Please see https://github.com/microsoft/dev-tunnels/issues/263#issuecomment-1608243688
