### ISSUE TITLE
TOS PDF is rights management protected

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/dev-tunnels#483]
https://aka.ms/devtunnels/tos this document is rights protected 
![image](https://github.com/user-attachments/assets/6e8e1d98-9f87-402d-9c4b-c78b296fa85b)

Remove the rights protection so it can actually be read.

**Comment by derekbekoe** [comment]
Thanks for raising this. We'll take a look.

**Comment by derekbekoe** [comment]
We've fix this now. Let us know if you still see issues with it.
