### ISSUE TITLE
Licensing: SDK Cannot be used Outside Visual Studio?

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/dev-tunnels#489]
https://download.microsoft.com/download/e/3/f/e3f44a20-7c3f-45fa-b3d0-dc2547545c0a/Dev%20Tunnels%20EULA.pdf

```
General. Microsoft grants you a personal, nonexclusive, nontransferable license to access, 
install, and use any number of copies of the software only with Microsoft Visual Studio and 
successor Microsoft products and services to develop and test your applications.
```

What's the point of providing an SDK if we cannot use it outside Visual Studio? The SDK license is MIT but since the devtunnels service is the only thing it can be used with and you do not provide a server implementation, it is effectively useless.

I would like to build a PowerShell module that leverages devtunnels to establish remoting connections and expose ports for development. According to your licensing, I cannot do that unless you consider PowerShell to be a "successor Microsoft product or service". 

Along these lines, is VSCode considered a "successor product"? I've always heard it referenced as complimentary and not a replacement for Visual Studio, and it implements devtunnels, so by that definition, VSCode is violating this license.
https://code.visualstudio.com/docs/remote/tunnels

@burkeholland any thoughts here?

**Comment by JustinGrote** [comment]
@jasongin @jfullerton44 open for two weeks, can we get some clarification here? The SDK is pretty much unusable as is without this clarification.

**Comment by jfullerton44** [comment]
Thank you for bringing this to our attention. We will look into this and get back to you

**Comment by JustinGrote** [comment]
@jfullerton following up again :)

**Comment by jfullerton44** [comment]
Hi Justin, unfortunately, at this time we are unable to modify the license for use outside of the Visual Studio family of products. The term “Visual Studio” in this Dev Tunnels public preview license was meant to cover the Visual Studio Products and Services family of products which includes Microsoft Visual Studio, Visual Studio for Mac, Visual Studio Code, Codespaces, Azure DevOps, Team Foundation Server, and successor Microsoft products and services.

**Comment by JustinGrote** [comment]
@jfullerton44 thank you.
Would utilization inside a PowerShell terminal inside of Visual Studio Code be considered "inside the Visual Studio Family of Products?"
![Image](https://github.com/user-attachments/assets/1cf092c6-bac7-47a4-97ea-be178bc3c6e3)

**Comment by jfullerton44** [comment]
Use for development inside VSCode should be allowed
