### ISSUE TITLE
DevTunnel websocket doesn't upgrade from HTTPS to WSS

### ISSUE THREAD

**Issue by iMicknl** [microsoft/dev-tunnels#501]
While using devtunnels it seems that my incoming websocket requests are not being upgraded from the HTTPs protocol to the WSS protocol. Not sure how I can debug this further?

## Steps
1. `devtunnel create --allow-anonymous`
2. `devtunnel port create -p 5000`
3. `devtunnel host`

Tested the same code directly to localhost and with ngrok, and this works without any issues.

**Comment by gokulbeeshman** [comment]
Facing this problem as well

**Comment by CharlieDigital** [comment]
Is this why SignalR doesn't work through `devtunnels.ms`?

**Comment by derekbekoe** [comment]
You may be running into this issue but without more context, it's hard to say.

Can you review this comment and let us know if that appears relevant here for you?
https://github.com/microsoft/dev-tunnels/issues/263#issuecomment-1608243688

**Comment by CharlieDigital** [comment]
@derekbekoe I've started by tunnels via VSC.

I have a tunnel that looks like this: `https://4gch1234-5081.use.devtunnels.ms/`

When I install and run `devtunnel connect 4gch1234`, I get a message `Tunnel not found`

The documentation is not clear for the operating conditions for this CLI command (and whether it works with the VSC extension functionality?)

**Comment by iMicknl** [comment]
@CharlieDigital not sure if I understand what `devtunnel connect [tunnel-id]` is supposed to do, but aren't you supposed to run this on the location (client) where you want to connect to the DevTunnel? In most cases where you want to run a devtunnel, this is not possible (e.g. Azure Communication Services, Azure Bot Service).

Since WebSockets are designed to work over HTTP/1.1 as well, I am not sure if this is the root cause to this issue.. Anything I can do to debug this problem?

**Comment by CharlieDigital** [comment]
Easiest repro is to just try it with a bare bones SignalR project :)
(It doesn't seem to work)

**Comment by iMicknl** [comment]
Sorry, my comment was not related to SignalR (as I am not using SignalR), but just a simple regular WebSocket connection. I accidentally tagged you in an early version of my post 😉.

**Comment by derekbekoe** [comment]
There may be a couple different things going on here. To better track and to avoid confusion, @CharlieDigital and @gokulbeeshman I'd suggest creating separate issues with as much context as you can provide so we can respond to each of you individually.

--

We do not support HTTP/2 on `*.devtunnels.ms`. For that to work, you'd have to run `devtunnel connect [tunnel-id]` on the client machine. Then, you could access the tunnel via localhost on that client machine and HTTP/2 would work fine in that case.

We do fully support WSS over HTTP/1.1. I just tested this with a sample React web app.
@iMicknl if you're not able to do this, please share more on your setup.

**Comment by iMicknl** [comment]
While working on the bug repro, it seems that there are no issues indeed. Retested my original solution and I don't face any issues anymore. Most likely just a fluke/error on my side!

Thanks for the support!
